name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm build
